// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using SportCommunityRM.Data;
using SportCommunityRM.Data.Models;
using System;

namespace SportCommunityRM.Data.Migrations
{
    [DbContext(typeof(SCRMContext))]
    partial class SCRMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportCommunityRM.Data.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<Guid?>("FieldId");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<DateTime>("StartDate");

                    b.Property<Guid?>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("TeamId");

                    b.ToTable("SCRM_Activities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Activity");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("LocationId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("SCRM_Fields");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Inscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("AmountDue");

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("InsertionDate");

                    b.Property<decimal?>("PartialAmount");

                    b.Property<DateTime>("StartDate");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SCRM_Inscriptions");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("CivicNumber");

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SCRM_Addresses");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.MedicalCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("InsertionDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SCRM_MedicalCertificates");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.RegisteredUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AspNetUserId")
                        .IsRequired();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int>("Sex");

                    b.Property<Guid?>("TeamId");

                    b.Property<Guid?>("TeamId1");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId1");

                    b.ToTable("SCRM_RegisteredUsers");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MaxBirthYear");

                    b.Property<int?>("MinBirthYear");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SCRM_Teams");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Match", b =>
                {
                    b.HasBaseType("SportCommunityRM.Data.Models.Activity");

                    b.Property<string>("EnemyTeamName");

                    b.Property<int>("EnemyTeamScore");

                    b.Property<int>("TeamScore");

                    b.ToTable("SCRM_Matches");

                    b.HasDiscriminator().HasValue("Match");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Tournament", b =>
                {
                    b.HasBaseType("SportCommunityRM.Data.Models.Activity");


                    b.ToTable("SCRM_Tournaments");

                    b.HasDiscriminator().HasValue("Tournament");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Training", b =>
                {
                    b.HasBaseType("SportCommunityRM.Data.Models.Activity");


                    b.ToTable("SCRM_Workouts");

                    b.HasDiscriminator().HasValue("Training");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Activity", b =>
                {
                    b.HasOne("SportCommunityRM.Data.Models.Field", "Field")
                        .WithMany("BookedActivities")
                        .HasForeignKey("FieldId");

                    b.HasOne("SportCommunityRM.Data.Models.Team")
                        .WithMany("Calendar")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Field", b =>
                {
                    b.HasOne("SportCommunityRM.Data.Models.Location", "Location")
                        .WithMany("Fields")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.Inscription", b =>
                {
                    b.HasOne("SportCommunityRM.Data.Models.RegisteredUser", "User")
                        .WithMany("InscriptionsHistory")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.MedicalCertificate", b =>
                {
                    b.HasOne("SportCommunityRM.Data.Models.RegisteredUser", "User")
                        .WithMany("MedicalCertificatesHistory")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SportCommunityRM.Data.Models.RegisteredUser", b =>
                {
                    b.HasOne("SportCommunityRM.Data.Models.Team")
                        .WithMany("Coaches")
                        .HasForeignKey("TeamId");

                    b.HasOne("SportCommunityRM.Data.Models.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId1");
                });
#pragma warning restore 612, 618
        }
    }
}
